[dev]
command = "npm run build"
port = 5173
publish = "build"
functionsPort = 9999
autoLaunch = false
framework = "#static"

[functions]
directory = "functions"
external_node_modules = ["openai", "zod", "stripe", "resend"]
